# defaults:
#   - override hydra/job_logging: custom
# plugins: 
#   - filemanager
#   - sql
data_reader:
  type: core.sharedmemoryreader
  variables: [top_repos_per_topic, top_repos]
  behaviors: 
    type: core.concat
    instructions:
      axis: 0

data_writer:
  type: github.write

transformer:
  type: core.transformers.pipeline
  mode: 2
  transformers:
    - type: core.transformers.dummy

    
    

